### ISSUE TITLE
Doesn't work for non-lvalue assignment expressions

### ISSUE THREAD

**Issue by chocolateboy** [lijinke666/babel-plugin-array-last-value#3]
This works:

```javascript
arr[-1] = 42 // arr[arr.length - 1] = 42
```

(The parent node is an [`AssignmentExpression`](https://astexplorer.net/#/gist/0d10b4163f733733471e75b895689fc4/e98384b46645097035dff54f3f275427bd38697c).)

And this works:

```javascript
let foo = arr[-1] // let foo = arr[arr.length - 1]
```

(The parent node is a [`VariableDeclarator`](https://astexplorer.net/#/gist/0d10b4163f733733471e75b895689fc4/b490a0da891beb537a4d31f3e9d3eddeec578763).)

But this doesn't work:

```javascript
foo = arr[-1] // foo = arr[-1]
```

(The parent node is an [`AssignmentExpression`](https://astexplorer.net/#/gist/0d10b4163f733733471e75b895689fc4/46d05ff69ebf0451c7c07d8de9dfa8adc72eb491).)

This condition is meant to exclude lvalue `MemberExpression`s (like the first example), which are handled separately, but also excludes these expressions, which should be included:

https://github.com/lijinke666/babel-plugin-array-last-index/blob/3d145fe634c11caeeb936d3cd94c560f6593ee1e/src/index.js#L32

---

- Babel: 7.7.4
- babel-plugin-array-last-index: 0.0.4
- OS: Linux (Arch)

**Comment by lijinke666** [comment]
@chocolateboy  thank your feedback. I will fix the bug as soon, add more test case : )

**Comment by lijinke666** [comment]
@chocolateboy fixed
